import { ConstructionActivity } from "./types";

export const activities: ConstructionActivity[] = [
  {
    id: "1",
    title: "Foundation & Excavation",
    project: "Green Valley Housing",
    block: "Block A",
    engineer: "Eng. Ahmed Khan",
    progress: 100,
    startDate: "2026-03-01",
    completionDate: "2026-03-15",
    workers: 25,
    status: "COMPLETED",
  },
  {
    id: "2",
    title: "Structure & Columns",
    project: "Green Valley Housing",
    block: "Block A",
    engineer: "Eng. Ahmed Khan",
    progress: 65,
    startDate: "2026-03-16",
    completionDate: "2026-04-30",
    workers: 40,
    status: "IN PROGRESS",
  },
  {
    id: "3",
    title: "Boundary Wall Construction",
    project: "Marina Heights",
    block: "Phase 1",
    engineer: "Eng. Sarah Ali",
    progress: 45,
    startDate: "2026-04-01",
    completionDate: "2026-04-20",
    workers: 15,
    status: "IN PROGRESS",
  },
  {
    id: "4",
    title: "Site Leveling",
    project: "Tech Park Commercial",
    block: "Main Area",
    engineer: "Eng. Bilal Hassan",
    progress: 0,
    startDate: "2026-05-01",
    completionDate: "2026-05-10",
    workers: 20,
    status: "NOT STARTED",
  },
  {
    id: "5",
    title: "Road Infrastructure",
    project: "Marina Heights",
    block: "Phase 1",
    engineer: "Eng. Sarah Ali",
    progress: 30,
    startDate: "2026-03-20",
    completionDate: "2026-05-15",
    workers: 12,
    status: "ON HOLD",
  },
];